---
- name: Open AMQP Ports
  when: rabbitmq.allow_amqp_cidrs is not undefined
  block:
  - name: Open AMQP SSL Port
    firewalld:
      rich_rule: "rule family=ipv4 source address={{item}} port port=5672 protocol=tcp accept"
      state: enabled
      permanent: yes
      immediate: yes
    loop: "{{ rabbitmq.allow_amqp_cidrs | flatten(levels=1) }}"
  - name: Open AMQP Port
    firewalld:
      rich_rule: "rule family=ipv4 source address={{item}} port port=5672 protocol=tcp accept"
      state: enabled
      permanent: yes
      immediate: yes
    loop: "{{ rabbitmq.allow_amqp_cidrs | flatten(levels=1) }}"

- name: Open Management Port
  when: "'rabbitmq_management' in rabbitmq.plugins and rabbitmq.allow_management_cidrs is not undefined"
  firewalld:
    rich_rule: "rule family=ipv4 source address={{item}} port port=15672 protocol=tcp accept"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ rabbitmq.allow_management_cidrs | flatten(levels=1) }}"

- name: Open MQTT Ports
  when: "'rabbitmq_mqtt' in rabbitmq.plugins and rabbitmq.allow_mqtt_cidrs is not undefined"
  block:
    - name: Open MQTT Port
      firewalld:
        rich_rule: "rule family=ipv4 source address={{item}} port port=1883 protocol=tcp accept"
        state: enabled
        permanent: yes
        immediate: yes
      loop: "{{ rabbitmq.allow_mqtt_cidrs | flatten(levels=1) }}"
    - name: Open MQTT SSL Port
      firewalld:
        rich_rule: "rule family=ipv4 source address={{item}} port port=8883 protocol=tcp accept"
        state: enabled
        permanent: yes
        immediate: yes
      loop: "{{ rabbitmq.allow_mqtt_cidrs | flatten(levels=1) }}"
