---
- name: Deploy rabbitmq.conf
  template:
    src: templates/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: rabbitmq
    group: rabbitmq
    mode: u=rw,g=r,o=r
  notify:
    - restart rabbitmq-server
