---
- name: Delete Management Firewall Zone
  command: firewall-cmd --permanent --delete-zone rabbitmq_mgmt
  register: delete_management_zone
  failed_when: delete_management_zone.rc != 0 and delete_management_zone.rc != 112
  changed_when: delete_management_zone.rc == 0

- name: Configure Firewall for Management
  when: "'rabbitmq_management' in rabbitmq.plugins"
  block:
    - name: Create Management Zone
      command: firewall-cmd --permanent --new-zone rabbitmq_mgmt
    - name: Enable Management Port
      firewalld:
        source: "{{item}}"
        port: 15672/tcp
        state: enabled
        permanent: yes
        immediate: yes
        zone: rabbitmq_mgmt
      loop: "{{ rabbitmq.allow_management_cidrs | flatten(levels=1) }}"
