---
- name: Delete Management Firewall Configuration
  when: "'rabbitmq_management' not in rabbitmq.plugins or rabbitmq.allow_management_cidrs is undefined"
  block:
    - name: Delete Management Firewall Zone
      command: firewall-cmd --permanent --delete-zone rabbitmq_mgmt
      register: delete_management_zone
      failed_when: delete_management_zone.rc != 0 and delete_management_zone.rc != 112
      changed_when: delete_management_zone.rc == 0
    - name: Reload Zones
      command: firewall-cmd --reload

- name: Create Management Firewall Configuration
  when: "'rabbitmq_management' in rabbitmq.plugins and rabbitmq.allow_management_cidrs is not undefined"
  block:
    - name: Create Management Zone
      command: firewall-cmd --permanent --new-zone rabbitmq_mgmt
    - name: Reload Zones
      command: firewall-cmd --reload
    - name: Enable Management Port
      firewalld:
        source: "{{ item }}"
        port: 15672/tcp
        state: enabled
        permanent: yes
        immediate: yes
        zone: rabbitmq_mgmt
      loop: "{{ rabbitmq.allow_management_cidrs | flatten(levels=1) }}"
