---
- name: Deploy rabbitmq.conf
  template:
    src: templates/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: rabbitmq
    group: rabbitmq
    mode: 0440
  notify:
    - restart rabbitmq-server
