---
- name: Open AMQP Port
  when: rabbitmq.config.listeners.tcp is defined
  firewalld:
    port: 5672/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close AMQP Port
  when: rabbitmq.config.listeners.tcp is not defined
  firewalld:
    port: 5672/tcp
    state: disabled
    permanent: true
    immediate: true

- name: Open AMQP SSL Port
  when: rabbitmq.config.listeners.ssl is defined
  firewalld:
    port: 5671/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close AMQP SSL Port
  when: rabbitmq.config.listeners.ssl is not defined
  firewalld:
    port: 5671/tcp
    state: disabled
    permanent: true
    immediate: true

- name: Open Management Port
  when: "'rabbitmq_management' in rabbitmq.plugins and rabbitmq.config.management.tcp.ip is defined"
  firewalld:
    port: 15672/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close Management Port
  when: "'rabbitmq_management' not in rabbitmq.plugins or rabbitmq.config.management.tcp.ip is not defined"
  firewalld:
    port: 15672/tcp
    state: disabled
    permanent: true
    immediate: true
  
- name: Open Management SSL Port
  when: "'rabbitmq_management' in rabbitmq.plugins and rabbitmq.config.management.ssl.certfile is defined"
  firewalld:
    port: 15671/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close Management SSL Port
  when: "'rabbitmq_management' not in rabbitmq.plugins or rabbitmq.config.management.ssl.certfile is not defined"
  firewalld:
    port: 15671/tcp
    state: disabled
    permanent: true
    immediate: true

- name: Open STOMP Port
  when: "'rabbitmq_stomp' in rabbitmq.plugins and rabbitmq.config.stomp.listeners.tcp is defined"
  firewalld:
    port: 61613/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close STOMP Port
  when: "'rabbitmq_stomp' not in rabbitmq.plugins or rabbitmq.config.stomp.listeners.tcp is not defined"
  firewalld:
    port: 61613/tcp
    state: disabled
    permanent: true
    immediate: true

- name: Open STOMP SSL Port
  when: "'rabbitmq_stomp' in rabbitmq.plugins and rabbitmq.config.stomp.listeners.ssl is defined"
  firewalld:
    port: 61614/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close STOMP SSL Port
  when: "'rabbitmq_stomp' not in rabbitmq.plugins or rabbitmq.config.stomp.listeners.ssl is not defined"
  firewalld:
    port: 61614/tcp
    state: disabled
    permanent: true
    immediate: true

- name: Open MQTT Port
  when: "'rabbitmq_mqtt' in rabbitmq.plugins and rabbitmq.config.mqtt.listeners.tcp is defined"
  firewalld:
    port: 1883/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close MQTT Port
  when: "'rabbitmq_mqtt' not in rabbitmq.plugins or rabbitmq.config.mqtt.listeners.tcp is not defined"
  firewalld:
    port: 1883/tcp
    state: disabled
    permanent: true
    immediate: true

- name: Open MQTT SSL Port
  when: "'rabbitmq_mqtt' in rabbitmq.plugins and rabbitmq.config.mqtt.listeners.ssl is defined"
  firewalld:
    port: 8883/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Close MQTT SSL Port
  when: "'rabbitmq_mqtt' not in rabbitmq.plugins or rabbitmq.config.mqtt.listeners.ssl is not defined"
  firewalld:
    port: 8883/tcp
    state: disabled
    permanent: true
    immediate: true